// Generated by Morphir Gleam Backend

pub fn prepend(values) {
  { let first = 1
  [first, ..values] }
}

pub fn first_or_zero(values) {
  case values { [first, .._] -> first [] -> 0 }
}

pub fn unpack(pair) {
  { let #(left, _) = pair
  left }
}

pub fn escaped() {
  "quote: \" slash: \\ line:\n"
}

pub fn whole_float() {
  1.0
}

