# GoReleaser configuration for Morphir Go
# See: https://goreleaser.com

version: 2

env:
  # Skip checksum verification for our own modules during release
  # This is needed because tags may not be indexed by sum.golang.org yet
  - GONOSUMDB=github.com/finos/morphir/*

before:
  hooks:
    # Safeguard: Remove any replace directives that may have been accidentally committed
    # This ensures go install compatibility
    - bash ./scripts/remove-replace-directives.sh
    # Sync CHANGELOG.md for embedding in about command
    - cp CHANGELOG.md cmd/morphir/cmd/CHANGELOG.md
    # Ensure all modules have their dependencies in order
    - go mod tidy -C cmd/morphir
    - go mod tidy -C pkg/models
    - go mod tidy -C pkg/nbformat
    - go mod tidy -C pkg/tooling
    - go mod tidy -C pkg/sdk
    - go mod tidy -C pkg/pipeline
    - go mod tidy -C tests/bdd
    - go work sync

builds:
  - id: morphir
    main: ./cmd/morphir
    binary: morphir
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/finos/morphir/cmd/morphir/cmd.Version={{.Version}}
      - -X github.com/finos/morphir/cmd/morphir/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/finos/morphir/cmd/morphir/cmd.BuildDate={{.Date}}
    # Ignore certain combinations that aren't supported
    ignore:
      # Windows doesn't support arm64 in GitHub Actions runners yet
      - goos: windows
        goarch: arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: false
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Others
      order: 999

release:
  github:
    owner: finos
    name: morphir
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ## Installation

    ### Binary Download
    Download the appropriate binary for your platform from the assets above.

    ### Using Go
    ```bash
    go install github.com/finos/morphir/cmd/morphir@{{.Tag}}
    ```

    ### Verifying Checksums
    ```bash
    sha256sum -c checksums.txt
    ```

    ---
    **Full Changelog**: https://github.com/finos/morphir/compare/{{ .PreviousTag }}...{{ .Tag }}
