//// Access control for the Morphir IR.
//// This module provides types for declaring access levels on types and values,
//// allowing modules to expose public interfaces while keeping implementations private.
// Generated by Morphir Gleam Backend

/// Access level for types and values.
pub type Access {
  Public
  Private
}

/// A value with an associated access level.
pub type AccessControlled(a) {
  AccessControlled(access: Access, value: a)
}

