//// The V3 library distribution. Dependencies carry public specifications.
// Generated by Morphir Gleam Backend

import gleam/dict
import morphir/ir/package
import morphir/ir/type_

pub type Distribution {
  Library(package_name: package.PackageName, dependencies: dict.Dict(package.PackageName, package.Specification(Nil)), definition: package.Definition(Nil, type_.Type(Nil)))
}

