//// Fully Qualified Name representation for the Morphir IR.
//// An FQName (Fully Qualified Name) combines a package path, module path,
//// and local name to uniquely identify any type or value across packages.
// Generated by Morphir Gleam Backend

import morphir/ir/name
import morphir/ir/path

/// An FQName is a fully qualified name consisting of:
/// - package_path: The path identifying the package
/// - module_path: The path identifying the module within the package
/// - local_name: The local name within the module
pub type FQName {
  FQName(package_path: path.Path, module_path: path.Path, local_name: name.Name)
}

