//// Literal values for the Morphir IR.
//// This module defines the types for representing fixed/constant values
//// in the IR, such as booleans, numbers, strings, and characters.
// Generated by Morphir Gleam Backend

/// A literal value representing a fixed/constant value in the IR.
pub type Literal {
  BoolLiteral(value: Bool)
  CharLiteral(value: String)
  StringLiteral(value: String)
  WholeNumberLiteral(value: Int)
  FloatLiteral(value: Float)
  DecimalLiteral(value: String)
}

