//// Module representation for the Morphir IR.
//// A module is a container for types and values within a package.
// Generated by Morphir Gleam Backend

import gleam/dict
import gleam/option
import morphir/ir/access_controlled
import morphir/ir/documented
import morphir/ir/name
import morphir/ir/path
import morphir/ir/type_
import morphir/ir/value

/// A module name is a Path identifying the module within a package.
pub type ModuleName = path.Path

/// A qualified module name combining package and module paths.
pub type QualifiedModuleName = #(path.Path, path.Path)

/// Module specification - the public interface of a module.
/// Contains only publicly exposed types and value signatures.
pub type Specification(ta) {
  Specification(types: dict.Dict(name.Name, documented.Documented(type_.Specification(ta))), values: dict.Dict(name.Name, documented.Documented(value.Specification(ta))), doc: option.Option(String))
}

/// Module definition - the complete implementation of a module.
/// Contains all types and values, including private ones.
pub type Definition(ta, va) {
  Definition(types: dict.Dict(name.Name, access_controlled.AccessControlled(documented.Documented(type_.Definition(ta)))), values: dict.Dict(name.Name, access_controlled.AccessControlled(documented.Documented(value.Definition(ta, va)))), doc: option.Option(String))
}

