//// Package representation for the Morphir IR.
//// A package is a collection of modules that are versioned together.
//// It represents a deployable unit of Morphir code.
// Generated by Morphir Gleam Backend

import gleam/dict
import morphir/ir/access_controlled
import morphir/ir/module
import morphir/ir/path

/// A package name is a Path that globally identifies the package.
pub type PackageName = path.Path

/// Package specification - the public interface of a package.
/// Contains only exposed module specifications.
pub type Specification(ta) {
  Specification(modules: dict.Dict(module.ModuleName, module.Specification(ta)))
}

/// Package definition - the complete implementation of a package.
/// Contains all modules, with access control.
pub type Definition(ta, va) {
  Definition(modules: dict.Dict(module.ModuleName, access_controlled.AccessControlled(module.Definition(ta, va))))
}

