//// Path representation for the Morphir IR.
//// A Path is a list of Names that identifies modules, packages, or other
//// hierarchical elements in the IR.
// Generated by Morphir Gleam Backend

import morphir/ir/name

/// A Path is a list of Names forming a hierarchical identifier.
pub type Path = List(name.Name)

