//// Qualified Name representation for the Morphir IR.
//// A QName (Qualified Name) combines a module path with a local name,
//// uniquely identifying a type or value within a module.
// Generated by Morphir Gleam Backend

import morphir/ir/name
import morphir/ir/path

/// A QName is a module path combined with a local name.
pub type QName {
  QName(module_path: path.Path, local_name: name.Name)
}

