//// Type representation for the Morphir IR.
//// This module defines the types for representing type expressions in the IR,
//// including variables, references, tuples, records, functions, and more.
// Generated by Morphir Gleam Backend

import gleam/dict
import morphir/ir/access_controlled
import morphir/ir/fqname
import morphir/ir/name

/// A field in a record type.
pub type Field(a) {
  Field(name: name.Name, tpe: Type(a))
}

/// A type expression in the Morphir IR.
/// The type parameter `a` represents attributes (like source location info).
pub type Type(a) {
  Variable(attributes: a, name: name.Name)
  Reference(attributes: a, type_name: fqname.FQName, type_arguments: List(Type(a)))
  Tuple(attributes: a, element_types: List(Type(a)))
  Record(attributes: a, fields: List(Field(a)))
  ExtensibleRecord(attributes: a, variable_name: name.Name, fields: List(Field(a)))
  Function(attributes: a, argument_type: Type(a), return_type: Type(a))
  Unit(attributes: a)
}

/// Constructor arguments: a list of (name, type) pairs.
pub type ConstructorArgs(a) = List(#(name.Name, Type(a)))

/// Constructors for a custom type: a dictionary from constructor name to its arguments.
pub type Constructors(a) = dict.Dict(name.Name, ConstructorArgs(a))

/// Details for a derived type specification.
pub type DerivedTypeSpecificationDetails(a) {
  DerivedTypeSpecificationDetails(base_type: Type(a), from_base_type: fqname.FQName, to_base_type: fqname.FQName)
}

/// Type specification - the public interface of a type.
pub type Specification(a) {
  TypeAliasSpecification(type_params: List(name.Name), tpe: Type(a))
  OpaqueTypeSpecification(type_params: List(name.Name))
  CustomTypeSpecification(type_params: List(name.Name), constructors: Constructors(a))
  DerivedTypeSpecification(type_params: List(name.Name), details: DerivedTypeSpecificationDetails(a))
}

/// Type definition - the full implementation of a type.
pub type Definition(a) {
  TypeAliasDefinition(type_params: List(name.Name), tpe: Type(a))
  CustomTypeDefinition(type_params: List(name.Name), constructors: access_controlled.AccessControlled(Constructors(a)))
}

/// One named constructor and its arguments.
pub type Constructor(a) = #(name.Name, ConstructorArgs(a))

