//// Value representation for the Morphir IR.
//// This module defines the types for representing value expressions (business logic)
//// in the IR, including literals, function applications, pattern matching, and more.
// Generated by Morphir Gleam Backend

import gleam/dict
import morphir/ir/fqname
import morphir/ir/literal
import morphir/ir/name
import morphir/ir/type_

/// A pattern for pattern matching.
/// The type parameter `a` represents attributes (like source location info).
pub type Pattern(a) {
  WildcardPattern(attributes: a)
  AsPattern(attributes: a, pattern: Pattern(a), name: name.Name)
  TuplePattern(attributes: a, element_patterns: List(Pattern(a)))
  ConstructorPattern(attributes: a, constructor_name: fqname.FQName, argument_patterns: List(Pattern(a)))
  EmptyListPattern(attributes: a)
  HeadTailPattern(attributes: a, head_pattern: Pattern(a), tail_pattern: Pattern(a))
  LiteralPattern(attributes: a, value: literal.Literal)
  UnitPattern(attributes: a)
}

/// A value definition (function or constant implementation).
/// - `ta` is the type attributes
/// - `va` is the value attributes
pub type Definition(ta, va) {
  Definition(input_types: List(#(name.Name, va, type_.Type(ta))), output_type: type_.Type(ta), body: Value(ta, va))
}

/// A value specification (type signature without implementation).
pub type Specification(a) {
  Specification(inputs: List(#(name.Name, type_.Type(a))), output: type_.Type(a))
}

/// A value expression in the Morphir IR.
/// - `ta` is the type attributes
/// - `va` is the value attributes
pub type Value(ta, va) {
  Literal(attributes: va, value: literal.Literal)
  Constructor(attributes: va, constructor_name: fqname.FQName)
  Tuple(attributes: va, elements: List(Value(ta, va)))
  List(attributes: va, items: List(Value(ta, va)))
  Record(attributes: va, fields: dict.Dict(name.Name, Value(ta, va)))
  Variable(attributes: va, name: name.Name)
  Reference(attributes: va, value_name: fqname.FQName)
  Field(attributes: va, record: Value(ta, va), field_name: name.Name)
  FieldFunction(attributes: va, field_name: name.Name)
  Apply(attributes: va, function: Value(ta, va), argument: Value(ta, va))
  Lambda(attributes: va, argument_pattern: Pattern(va), body: Value(ta, va))
  LetDefinition(attributes: va, name: name.Name, definition: Definition(ta, va), in_value: Value(ta, va))
  LetRecursion(attributes: va, definitions: dict.Dict(name.Name, Definition(ta, va)), in_value: Value(ta, va))
  Destructure(attributes: va, pattern: Pattern(va), value_to_destructure: Value(ta, va), in_value: Value(ta, va))
  IfThenElse(attributes: va, condition: Value(ta, va), then_branch: Value(ta, va), else_branch: Value(ta, va))
  PatternMatch(attributes: va, value: Value(ta, va), cases: List(#(Pattern(va), Value(ta, va))))
  UpdateRecord(attributes: va, record: Value(ta, va), fields_to_update: dict.Dict(name.Name, Value(ta, va)))
  Unit(attributes: va)
}

/// An expression with no type or value attributes.
pub type RawValue = Value(Nil, Nil)

/// An expression annotated with its inferred types.
pub type TypedValue = Value(Nil, type_.Type(Nil))

