package morphir:platform@0.1.0;

interface project {
  record project-info {
     name: string,
     source-directory: string,
     includes: list<string>,
     dependencies: list<string>,
     local-dependencies: list<string>,
  }

  get-project-info: func(project-dir:string) -> result<project-info>;

}

interface workspace {}

interface command-runner {  
  run: func(args:list<string>) -> result<string, string>; 
}

/// An example world for the component to target.
world main {
    export workspace;
    export project;
    export command-runner;
}
