/**
 * Generate styles object for IR Checker components
 */

import type { CreateStylesParams, IRCheckerStyles } from './types';

export function createStyles({
  colorMode,
  sidebarWidth,
  xrayWidth,
  isDragging,
  isDraggingXray,
  validationResult,
}: CreateStylesParams): IRCheckerStyles {
  return {
    container: {
      display: 'flex',
      flexDirection: 'column',
      height: 'calc(100vh - 60px)',
      backgroundColor: colorMode === 'dark' ? '#1e1e1e' : '#ffffff',
    },
    toolbar: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.75rem',
      padding: '0.5rem 1rem',
      borderBottom: `1px solid ${colorMode === 'dark' ? '#333' : '#e0e0e0'}`,
      backgroundColor: colorMode === 'dark' ? '#252526' : '#f3f3f3',
      flexWrap: 'wrap',
    },
    toolbarGroup: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
    },
    toolbarLabel: {
      fontSize: '0.85rem',
      color: colorMode === 'dark' ? '#ccc' : '#666',
    },
    versionBtn: (isSelected) => ({
      padding: '0.25rem 0.75rem',
      fontSize: '0.85rem',
      border: `1px solid ${isSelected ? '#0078d4' : (colorMode === 'dark' ? '#555' : '#ccc')}`,
      borderRadius: '3px',
      backgroundColor: isSelected ? '#0078d4' : 'transparent',
      color: isSelected ? '#fff' : (colorMode === 'dark' ? '#ccc' : '#333'),
      cursor: 'pointer',
    }),
    toolbarBtn: {
      padding: '0.25rem 0.75rem',
      fontSize: '0.85rem',
      border: `1px solid ${colorMode === 'dark' ? '#555' : '#ccc'}`,
      borderRadius: '3px',
      backgroundColor: 'transparent',
      color: colorMode === 'dark' ? '#ccc' : '#333',
      cursor: 'pointer',
    },
    mainContent: {
      display: 'flex',
      flex: 1,
      overflow: 'hidden',
    },
    editorPane: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      minWidth: 0,
    },
    splitter: {
      width: '6px',
      cursor: 'col-resize',
      backgroundColor: isDragging
        ? '#0078d4'
        : (colorMode === 'dark' ? '#333' : '#e0e0e0'),
      transition: isDragging ? 'none' : 'background-color 0.2s',
      flexShrink: 0,
    },
    editorHeader: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0.5rem 1rem',
      backgroundColor: colorMode === 'dark' ? '#2d2d2d' : '#f8f8f8',
      borderBottom: `1px solid ${colorMode === 'dark' ? '#333' : '#e0e0e0'}`,
      fontSize: '0.85rem',
      color: colorMode === 'dark' ? '#ccc' : '#666',
    },
    sidebar: {
      width: `${sidebarWidth}px`,
      display: 'flex',
      flexDirection: 'column',
      backgroundColor: colorMode === 'dark' ? '#252526' : '#f8f8f8',
      flexShrink: 0,
    },
    sidebarHeader: {
      padding: '0.5rem 1rem',
      borderBottom: `1px solid ${colorMode === 'dark' ? '#333' : '#e0e0e0'}`,
      fontWeight: 'bold',
      fontSize: '0.9rem',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '0.5rem',
    },
    sidebarHeaderLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
    },
    sidebarHeaderButtons: {
      display: 'flex',
      gap: '0.25rem',
    },
    iconBtn: {
      padding: '0.25rem 0.5rem',
      fontSize: '0.75rem',
      border: `1px solid ${colorMode === 'dark' ? '#555' : '#ccc'}`,
      borderRadius: '3px',
      backgroundColor: 'transparent',
      color: colorMode === 'dark' ? '#ccc' : '#666',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '0.25rem',
    },
    sidebarContent: {
      flex: 1,
      overflow: 'auto',
      padding: '0.5rem',
    },
    card: (type) => ({
      backgroundColor: colorMode === 'dark' ? '#2d2d2d' : '#fff',
      border: `1px solid ${type === 'error' ? '#f44336' : type === 'success' ? '#4caf50' : (colorMode === 'dark' ? '#444' : '#ddd')}`,
      borderLeft: `3px solid ${type === 'error' ? '#f44336' : type === 'success' ? '#4caf50' : '#2196f3'}`,
      borderRadius: '4px',
      marginBottom: '0.5rem',
      overflow: 'hidden',
    }),
    cardHeader: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0.5rem 0.75rem',
      backgroundColor: colorMode === 'dark' ? '#333' : '#f5f5f5',
      borderBottom: `1px solid ${colorMode === 'dark' ? '#444' : '#eee'}`,
      cursor: 'pointer',
      userSelect: 'none',
    },
    cardTitle: {
      fontSize: '0.8rem',
      fontWeight: 'bold',
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
    },
    cardToggle: {
      fontSize: '0.7rem',
      color: colorMode === 'dark' ? '#888' : '#666',
      marginRight: '0.5rem',
      transition: 'transform 0.2s',
    },
    cardMeta: {
      fontSize: '0.75rem',
      color: colorMode === 'dark' ? '#888' : '#999',
    },
    pathLink: {
      fontSize: '0.75rem',
      color: '#0078d4',
      cursor: 'pointer',
      fontFamily: 'monospace',
      backgroundColor: colorMode === 'dark' ? '#1e1e1e' : '#f0f0f0',
      padding: '0.1rem 0.4rem',
      borderRadius: '3px',
      display: 'inline-block',
      marginTop: '0.25rem',
    },
    cardBody: {
      padding: '0.75rem',
      fontSize: '0.85rem',
      fontFamily: 'monospace',
    },
    badge: (color) => ({
      display: 'inline-block',
      padding: '0.15rem 0.5rem',
      borderRadius: '10px',
      fontSize: '0.7rem',
      fontWeight: 'bold',
      backgroundColor: color,
      color: '#fff',
    }),
    statusBar: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0.25rem 1rem',
      backgroundColor: validationResult?.valid ? '#4caf50' : (validationResult ? '#f44336' : '#0078d4'),
      color: '#fff',
      fontSize: '0.8rem',
    },
    xrayPanel: {
      width: `${xrayWidth}px`,
      display: 'flex',
      flexDirection: 'column',
      backgroundColor: colorMode === 'dark' ? '#1e1e1e' : '#fafafa',
      flexShrink: 0,
    },
    xrayHeader: {
      padding: '0.5rem 1rem',
      borderBottom: `1px solid ${colorMode === 'dark' ? '#333' : '#e0e0e0'}`,
      fontWeight: 'bold',
      fontSize: '0.9rem',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colorMode === 'dark' ? '#252526' : '#f0f0f0',
    },
    xrayContent: {
      flex: 1,
      overflow: 'auto',
      padding: '0.5rem',
    },
    xraySplitter: {
      width: '6px',
      cursor: 'col-resize',
      backgroundColor: isDraggingXray
        ? '#9c27b0'
        : (colorMode === 'dark' ? '#333' : '#e0e0e0'),
      transition: isDraggingXray ? 'none' : 'background-color 0.2s',
      flexShrink: 0,
    },
    xrayToggleBtn: (isActive) => ({
      padding: '0.25rem 0.75rem',
      fontSize: '0.85rem',
      border: `1px solid ${isActive ? '#9c27b0' : (colorMode === 'dark' ? '#555' : '#ccc')}`,
      borderRadius: '3px',
      backgroundColor: isActive ? '#9c27b0' : 'transparent',
      color: isActive ? '#fff' : (colorMode === 'dark' ? '#ccc' : '#333'),
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '0.25rem',
    }),
  };
}
