fileGroups:
  morphirProjectFiles:
    - "morphir.json"
  morphirElmSources:
    - "src/**/*.elm"
  morphirElmArtifacts:
    - "morphir-hashes.json"
    - "morphir-ir.json"

tasks:
  morphir-elm-build:
    deps:
      - "~:morphir-elm-make"

  morphir-elm-rebuild:
    deps:
      - "~:morphir-elm-clean"
      - "~:morphir-elm-build"

  morphir-elm-clean:
    command: |
      rm -rf @files(morphirElmArtifacts)
    inputs:
      - "@files(morphirElmArtifacts)"

  morphir-elm-make:
    command: |
      morphir make
    inputs:
      - "@files(morphirProjectFiles)"
      - "@files(morphirElmArtifacts)"
      - "package.json"
      - "@files(morphirElmSources)"
    outputs:
      - "morphir-hashes.json"
      - "morphir-ir.json"

  clean:
    deps:
      - target: "~:morphir-elm-clean"
