# @generated by usage-cli from docs/cli/morphir.usage.kdl

# if "usage" is not installed show an error
if ! type -P usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in morphir." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_morphir 'name morphir
bin morphir
version "0.4.0-alpha.5"
about "CLI for working with Morphir IR - functional domain modeling and business logic"
unknown_flags error
disable_version_flag #true
args_override_self #false
usage "Usage: morphir [OPTIONS] [COMMAND]"
flag --help-all help="Print help including experimental commands"
flag "-V --version" help="Print version" action=version
cmd compile display_order=2 args_override_self=#false help="Compile source code to Morphir IR" unknown_flags=error {
    flag "-l --language" help="Source language (e.g., gleam, elm)" {
        arg <LANGUAGE>
    }
    flag "-i --input" help="Input source directory or file" {
        arg <INPUT>
    }
    flag "-o --output" help="Output directory" {
        arg <OUTPUT>
    }
    flag --package-name help="Package name override" {
        arg <PACKAGE_NAME>
    }
    flag --config help="Explicit config file path" {
        arg <CONFIG>
    }
    flag --project help="Project name (for workspaces)" {
        arg <PROJECT>
    }
    flag --json help="Output as JSON"
    flag --json-lines help="Output as JSON Lines (streaming)"
}
cmd generate display_order=3 args_override_self=#false help="Generate code from Morphir IR" unknown_flags=error {
    flag "-t --target" help="Target language or format" {
        arg <TARGET>
    }
    flag "-i --input" help="Path to the Morphir IR file or directory" {
        arg <INPUT>
    }
    flag "-o --output" help="Output directory" {
        arg <OUTPUT>
    }
    flag --config help="Explicit config file path" {
        arg <CONFIG>
    }
    flag --project help="Project name (for workspaces)" {
        arg <PROJECT>
    }
    flag --json help="Output as JSON"
    flag --json-lines help="Output as JSON Lines (streaming)"
}
cmd validate hide=#true display_order=4 args_override_self=#false help="[Experimental] Validate Morphir IR models" unknown_flags=error {
    flag "-i --input" help="Path to the Morphir IR file or directory" {
        arg <INPUT>
    }
}
cmd transform hide=#true display_order=5 args_override_self=#false help="[Experimental] Transform Morphir IR" unknown_flags=error {
    flag "-i --input" help="Path to the Morphir IR file or directory" {
        arg <INPUT>
    }
    flag "-o --output" help="Output path" {
        arg <OUTPUT>
    }
}
cmd config display_order=6 subcommand_required=#true arg_required_else_help=#true args_override_self=#false help="Inspect the effective Morphir configuration" unknown_flags=error {
    cmd get display_order=0 args_override_self=#false help="Get one value from the effective configuration" unknown_flags=error {
        flag --config help="Explicit project config file path" {
            arg <CONFIG>
        }
        flag --json help="Output as JSON"
        flag --isolated help="Ignore machine-level and user-level configuration sources" hide=#true
        arg <KEY> help="Dotted configuration key, such as project.name"
    }
    cmd show display_order=1 args_override_self=#false help="Show the effective configuration after merging every source" unknown_flags=error {
        flag --config help="Explicit project config file path" {
            arg <CONFIG>
        }
        flag --json help="Output as JSON"
        flag --isolated help="Ignore machine-level and user-level configuration sources" hide=#true
    }
    cmd path display_order=2 args_override_self=#false help="Show which configuration sources were considered" unknown_flags=error {
        flag --config help="Explicit project config file path" {
            arg <CONFIG>
        }
        flag --json help="Output as JSON"
        flag --isolated help="Ignore machine-level and user-level configuration sources" hide=#true
    }
}
cmd tool display_order=7 subcommand_required=#true arg_required_else_help=#true args_override_self=#false help="Manage Morphir tools, distributions, and extensions" unknown_flags=error {
    cmd install display_order=0 args_override_self=#false help="Install a Morphir tool or extension" unknown_flags=error {
        flag "-v --version" help="Version to install (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the tool to install"
    }
    cmd list display_order=1 args_override_self=#false help="List installed Morphir tools" unknown_flags=error
    cmd update display_order=2 args_override_self=#false help="Update an installed Morphir tool" unknown_flags=error {
        flag "-v --version" help="Version to update to (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the tool to update"
    }
    cmd uninstall display_order=3 args_override_self=#false help="Uninstall a Morphir tool" unknown_flags=error {
        arg <NAME> help="Name of the tool to uninstall"
    }
}
cmd dist display_order=8 subcommand_required=#true arg_required_else_help=#true args_override_self=#false help="Manage Morphir distributions" unknown_flags=error {
    cmd install display_order=0 args_override_self=#false help="Install a Morphir distribution" unknown_flags=error {
        flag "-v --version" help="Version to install (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the distribution to install"
    }
    cmd list display_order=1 args_override_self=#false help="List installed Morphir distributions" unknown_flags=error
    cmd update display_order=2 args_override_self=#false help="Update an installed Morphir distribution" unknown_flags=error {
        flag "-v --version" help="Version to update to (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the distribution to update"
    }
    cmd uninstall display_order=3 args_override_self=#false help="Uninstall a Morphir distribution" unknown_flags=error {
        arg <NAME> help="Name of the distribution to uninstall"
    }
}
cmd extension display_order=9 subcommand_required=#true arg_required_else_help=#true args_override_self=#false help="Manage Morphir extensions" unknown_flags=error {
    cmd install display_order=0 args_override_self=#false help="Install a Morphir extension" unknown_flags=error {
        flag "-v --version" help="Version to install (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the extension to install"
    }
    cmd list display_order=1 args_override_self=#false help="List installed Morphir extensions" unknown_flags=error
    cmd update display_order=2 args_override_self=#false help="Update an installed Morphir extension" unknown_flags=error {
        flag "-v --version" help="Version to update to (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the extension to update"
    }
    cmd uninstall display_order=3 args_override_self=#false help="Uninstall a Morphir extension" unknown_flags=error {
        arg <NAME> help="Name of the extension to uninstall"
    }
}
cmd ir display_order=10 subcommand_required=#true arg_required_else_help=#true args_override_self=#false help="Manage Morphir IR" unknown_flags=error {
    cmd migrate display_order=0 args_override_self=#false help="Migrate IR between versions" unknown_flags=error {
        long_help #"""
Migrate IR between versions

Converts Morphir IR between Classic (V1-V3) and V4 formats. Supports local files, URLs, and GitHub shorthand sources.

**Examples:**

```bash
# Migrate to file
morphir ir migrate ./morphir-ir.json -o ./morphir-ir-v4.json --target-version v4

# Migrate from URL
morphir ir migrate https://lcr-interactive.finos.org/server/morphir-ir.json -o ./lcr-v4.json

# Display in console with syntax highlighting (no -o)
morphir ir migrate ./morphir-ir.json

# Downgrade V4 to Classic
morphir ir migrate ./morphir-ir-v4.json -o ./morphir-ir-classic.json --target-version classic
```

See the [IR Migration Guide](https://morphir.finos.org/docs/user-guides/cli-tools/ir-migrate) for detailed real-world examples including the US Federal Reserve FR 2052a regulation model.
"""#
        flag "-o --output" help="Output file or directory (if omitted, displays in console with syntax highlighting)" {
            arg <OUTPUT>
        }
        flag --target-version help="Target version: latest, v4/4, classic, v3/3, v2/2, v1/1 (default: latest)" default=latest {
            arg <TARGET_VERSION>
        }
        flag --force-refresh help="Force refresh cached remote sources"
        flag --no-cache help="Skip cache entirely for remote sources"
        flag --json help="Output result as JSON (for scripting)"
        flag --expanded help="Use expanded (non-compact) format for V4 output"
        arg <INPUT> help="Input file, directory, or remote source (e.g., github:owner/repo, URL)"
        complete output type=path
    }
}
cmd gleam display_order=11 subcommand_required=#true arg_required_else_help=#true args_override_self=#false help="Gleam language binding commands" unknown_flags=error {
    flag --json help="Output as JSON"
    flag --json-lines help="Output as JSON Lines (streaming)"
    cmd compile display_order=0 args_override_self=#false help="Compile Gleam source to Morphir IR" unknown_flags=error {
        flag "-i --input" help="Input source directory or file" {
            arg <INPUT>
        }
        flag "-o --output" help="Output directory" {
            arg <OUTPUT>
        }
        flag --package-name help="Package name override" {
            arg <PACKAGE_NAME>
        }
        flag --config help="Explicit config file path" {
            arg <CONFIG>
        }
        flag --project help="Project name (for workspaces)" {
            arg <PROJECT>
        }
    }
    cmd generate display_order=1 args_override_self=#false help="Generate Gleam code from Morphir IR" unknown_flags=error {
        flag "-i --input" help="Path to the Morphir IR file or directory" {
            arg <INPUT>
        }
        flag "-o --output" help="Output directory" {
            arg <OUTPUT>
        }
        flag --config help="Explicit config file path" {
            arg <CONFIG>
        }
        flag --project help="Project name (for workspaces)" {
            arg <PROJECT>
        }
    }
    cmd roundtrip display_order=2 args_override_self=#false help="Roundtrip: compile then generate (for testing)" unknown_flags=error {
        flag "-i --input" help="Input source directory or file" {
            arg <INPUT>
        }
        flag "-o --output" help="Output directory" {
            arg <OUTPUT>
        }
        flag --package-name help="Package name override" {
            arg <PACKAGE_NAME>
        }
        flag --config help="Explicit config file path" {
            arg <CONFIG>
        }
        flag --project help="Project name (for workspaces)" {
            arg <PROJECT>
        }
    }
}
cmd schema display_order=12 args_override_self=#false help="Generate JSON Schema for Morphir IR" unknown_flags=error {
    flag "-o --output" help="Output file path (optional)" {
        arg <OUTPUT>
    }
    complete output type=path
}
cmd version display_order=13 args_override_self=#false help="Print version information" unknown_flags=error {
    flag --json help="Output version info as JSON"
}
cmd usage hide=#true display_order=14 args_override_self=#false help="Output usage spec for documentation generation" unknown_flags=error
'
set -l spec_dir (if set -q XDG_CACHE_HOME; echo $XDG_CACHE_HOME; else; echo $HOME/.cache; end)/usage
test -d "$spec_dir"; or mkdir -p -m 700 "$spec_dir"
set -l spec_file "$spec_dir/usage__usage_spec_morphir.spec"
echo $_usage_spec_morphir > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc morphir -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc morphir -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
