// Generates spec/mck/vocabulary.json, the parent-owned coverage vocabulary the
// Rust `morphir mck` tooling reads (spec/mck/kit-manifest.md, closure item 3).
//
// The TypeScript IR model owns the authoring table. This renders VOCABULARY,
// NODE_ALIASES and the adapter's NODE_KINDS into language-neutral JSON.
// Native coverage reads the committed data; --check detects authoring drift.
// This generator contains no compatibility execution or comparison logic.
//
//   bun run tools/gen-mck-vocabulary.ts          # rewrite the file
//   bun run tools/gen-mck-vocabulary.ts --check  # fail on drift
//
// The table import needs the morphir-typescript workspace installed
// (`bun install --cwd ecosystem/morphir-typescript`), so it happens inside
// main; the rendering below is pure and unit-tested on its own.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

export const VOCABULARY_PATH = "spec/mck/vocabulary.json";

export interface Spelling {
	readonly name: string;
	readonly spelling: "canonical" | "legacy";
}

export interface Entry {
	readonly node: string;
	readonly variant: string;
	readonly members: readonly Spelling[];
}

export interface Tables {
	readonly nodes: readonly string[];
	readonly aliases: Readonly<Record<string, string>>;
	readonly entries: readonly Entry[];
}

/** The committed JSON for `tables`: tab-indented with a trailing newline, entries in table order. */
export function renderVocabulary(tables: Tables): string {
	const unknown = tables.entries.map((e) => e.node).filter((node) => !tables.nodes.includes(node));
	if (unknown.length > 0) throw new Error(`vocabulary names unknown node kinds: ${[...new Set(unknown)].join(", ")}`);
	for (const [alias, node] of Object.entries(tables.aliases)) {
		if (!tables.nodes.includes(node)) throw new Error(`alias ${alias} names unknown node kind ${node}`);
	}
	const document = {
		vocabularyVersion: 1,
		irVersion: 4,
		description:
			"Every IR v4 node variant a reader recognizes and every member spelling it accepts. `morphir mck coverage` reports a gap for any entry with no kit case. Generated by tools/gen-mck-vocabulary.ts; do not edit by hand.",
		nodes: tables.nodes,
		aliases: Object.fromEntries(Object.entries(tables.aliases).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))),
		entries: tables.entries.map((e) => ({ node: e.node, variant: e.variant, members: e.members.map((m) => ({ name: m.name, spelling: m.spelling })) })),
	};
	return `${JSON.stringify(document, null, "\t")}\n`;
}

async function loadTables(): Promise<Tables> {
	const root = "../ecosystem/morphir-typescript/packages";
	const vocabulary = await import(`${root}/ir/src/versions/v4/vocabulary.ts`);
	const pinned = await import(`${root}/ir/src/versions/v4/index.ts`);
	const inProcess = await import(`${root}/mck/src/testee/in-process.ts`);
	return { nodes: inProcess.NODE_KINDS, aliases: pinned.NODE_ALIASES, entries: vocabulary.VOCABULARY };
}

if (import.meta.main) {
	const file = path.join(import.meta.dir, "..", VOCABULARY_PATH);
	const rendered = renderVocabulary(await loadTables());
	if (process.argv.includes("--check")) {
		const committed = readFileSync(file, "utf8").replaceAll("\r\n", "\n");
		if (committed !== rendered) {
			console.error(`${VOCABULARY_PATH} differs from the TypeScript vocabulary; run: bun run tools/gen-mck-vocabulary.ts`);
			process.exit(1);
		}
		console.log(`${VOCABULARY_PATH} matches the TypeScript vocabulary`);
	} else {
		writeFileSync(file, rendered);
		console.log(`wrote ${VOCABULARY_PATH}`);
	}
}
