import { createHash, randomUUID } from "node:crypto";
import {
	copyFileSync,
	existsSync,
	lstatSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	renameSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export interface WebAsset {
	readonly relativePath: string;
	readonly sha256: string;
	readonly size: number;
}

export interface WebAssetManifest {
	readonly assets: readonly WebAsset[];
	readonly manifestSha256: string;
}

export interface WebProvenance {
	readonly webVersion: string;
	readonly uiSourceCommit: string;
	readonly assetManifestSha256: string;
}

const SOURCE_COMMIT = /^[0-9a-f]{40}$/;
const SHA_256 = /^[0-9a-f]{64}$/;

export function validateSourceCommit(commit: string): string {
	const value = commit.trim();
	if (!SOURCE_COMMIT.test(value)) {
		throw new Error("UI source commit must be a lowercase 40-character Git commit");
	}
	return value;
}

export function assertCleanSource(status: string): void {
	if (status.trim().length !== 0) {
		throw new Error("morphir-ui source must have a clean working tree");
	}
}

function relativeFiles(root: string, directory = root): string[] {
	const result: string[] = [];
	for (const entry of readdirSync(directory, { withFileTypes: true })) {
		const absolutePath = path.join(directory, entry.name);
		const stat = lstatSync(absolutePath);
		if (stat.isSymbolicLink()) {
			throw new Error(`Web build contains a symbolic link: ${entry.name}`);
		}
		if (stat.isDirectory()) {
			result.push(...relativeFiles(root, absolutePath));
		} else if (stat.isFile()) {
			const relativePath = path.relative(root, absolutePath).split(path.sep).join("/");
			if (relativePath.endsWith(".map")) {
				throw new Error(`Web build contains a source map: ${relativePath}`);
			}
			result.push(relativePath);
		}
	}
	return result;
}

export async function collectWebAssets(
	buildDirectory: string,
): Promise<WebAssetManifest> {
	if (!existsSync(buildDirectory) || !lstatSync(buildDirectory).isDirectory()) {
		throw new Error(`Web build directory does not exist: ${buildDirectory}`);
	}

	const relativePaths = relativeFiles(buildDirectory).sort();
	if (!relativePaths.includes("index.html")) {
		throw new Error("Web build does not contain index.html");
	}

	const manifestHash = createHash("sha256");
	const assets = relativePaths.map((relativePath) => {
		const bytes = readFileSync(path.join(buildDirectory, ...relativePath.split("/")));
		manifestHash.update(relativePath, "utf8");
		manifestHash.update("\0");
		manifestHash.update(bytes);
		manifestHash.update("\0");
		return {
			relativePath,
			sha256: createHash("sha256").update(bytes).digest("hex"),
			size: bytes.length,
		};
	});

	return { assets, manifestSha256: manifestHash.digest("hex") };
}

function contentType(relativePath: string): string {
	const extension = path.extname(relativePath).toLowerCase();
	const known: Readonly<Record<string, string>> = {
		".css": "text/css; charset=utf-8",
		".gif": "image/gif",
		".html": "text/html; charset=utf-8",
		".ico": "image/x-icon",
		".jpeg": "image/jpeg",
		".jpg": "image/jpeg",
		".js": "text/javascript; charset=utf-8",
		".json": "application/json",
		".png": "image/png",
		".svg": "image/svg+xml",
		".wasm": "application/wasm",
		".webp": "image/webp",
		".woff": "font/woff",
		".woff2": "font/woff2",
	};
	const value = known[extension];
	if (value === undefined) {
		throw new Error(`No content type is defined for ${relativePath}`);
	}
	return value;
}

function rustString(value: string): string {
	return JSON.stringify(value);
}

function embeddedRust(manifest: WebAssetManifest): string {
	const arms = manifest.assets
		.map(({ relativePath }) => {
			const immutable = relativePath !== "index.html";
			return `        ${rustString(relativePath)} => Some(EmbeddedAsset { bytes: include_bytes!(${rustString(relativePath)}), content_type: ${rustString(contentType(relativePath))}, immutable: ${immutable} }),`;
		})
		.join("\n");
	return `// Generated by tools/vendor-morphir-web.ts. Do not edit.\n\npub(super) fn generated_asset(path: &str) -> Option<EmbeddedAsset> {\n    match path {\n${arms}\n        _ => None,\n    }\n}\n`;
}

function validateProvenance(provenance: WebProvenance): void {
	validateSourceCommit(provenance.uiSourceCommit);
	if (!SHA_256.test(provenance.assetManifestSha256)) {
		throw new Error("Asset manifest digest must be a lowercase SHA-256 digest");
	}
	if (provenance.webVersion.trim().length === 0) {
		throw new Error("Web version cannot be empty");
	}
}

export async function replaceVendoredAssets(options: {
	readonly buildDirectory: string;
	readonly destinationDirectory: string;
	readonly manifest: WebAssetManifest;
	readonly provenance: WebProvenance;
}): Promise<void> {
	validateProvenance(options.provenance);
	if (options.provenance.assetManifestSha256 !== options.manifest.manifestSha256) {
		throw new Error("Provenance does not match the web asset manifest");
	}

	const parent = path.dirname(options.destinationDirectory);
	const stem = path.basename(options.destinationDirectory);
	const staging = path.join(parent, `.${stem}.staging-${randomUUID()}`);
	const backup = path.join(parent, `.${stem}.backup-${randomUUID()}`);
	mkdirSync(staging, { recursive: false });

	try {
		for (const asset of options.manifest.assets) {
			const source = path.join(
				options.buildDirectory,
				...asset.relativePath.split("/"),
			);
			const destination = path.join(staging, ...asset.relativePath.split("/"));
			mkdirSync(path.dirname(destination), { recursive: true });
			copyFileSync(source, destination);
		}
		writeFileSync(
			path.join(staging, "provenance.json"),
			`${JSON.stringify(options.provenance, null, 2)}\n`,
		);
		writeFileSync(path.join(staging, "embedded.rs"), embeddedRust(options.manifest));

		const hadDestination = existsSync(options.destinationDirectory);
		if (hadDestination) renameSync(options.destinationDirectory, backup);
		try {
			renameSync(staging, options.destinationDirectory);
		} catch (error) {
			if (hadDestination) renameSync(backup, options.destinationDirectory);
			throw error;
		}
		if (hadDestination) rmSync(backup, { recursive: true });
	} finally {
		rmSync(staging, { force: true, recursive: true });
		rmSync(backup, { force: true, recursive: true });
	}
}

function run(command: readonly string[], cwd: string): string {
	const process = Bun.spawnSync([...command], {
		cwd,
		stderr: "inherit",
		stdout: "pipe",
	});
	if (process.exitCode !== 0) {
		throw new Error(`Command failed (${process.exitCode}): ${command.join(" ")}`);
	}
	return process.stdout.toString();
}

async function main(): Promise<void> {
	const sourceArgument = process.argv[2];
	if (sourceArgument === undefined) {
		throw new Error("Usage: vendor-morphir-web.ts <morphir-ui-worktree>");
	}
	const sourceRoot = path.resolve(sourceArgument);
	assertCleanSource(run(["git", "status", "--porcelain"], sourceRoot));
	const sourceCommit = validateSourceCommit(
		run(["git", "rev-parse", "HEAD"], sourceRoot),
	);
	const packageJson = JSON.parse(
		readFileSync(path.join(sourceRoot, "apps/morphir-web/package.json"), "utf8"),
	) as { version?: unknown };
	if (typeof packageJson.version !== "string") {
		throw new Error("@morphir/web package.json does not contain a version");
	}
	const buildDirectory = path.join(sourceRoot, "apps/morphir-web/dist");
	const buildCommand = [
		"mise",
		"exec",
		"--",
		"bun",
		"run",
		"--cwd",
		"apps/morphir-web",
		"build",
	] as const;
	run(buildCommand, sourceRoot);
	const first = await collectWebAssets(buildDirectory);
	run(buildCommand, sourceRoot);
	const second = await collectWebAssets(buildDirectory);
	if (JSON.stringify(first) !== JSON.stringify(second)) {
		throw new Error("Two morphir-web builds did not produce identical assets");
	}

	const toolsRoot = path.dirname(fileURLToPath(import.meta.url));
	const repositoryRoot = path.dirname(toolsRoot);
	const destinationDirectory = path.join(
		repositoryRoot,
		"crates/morphir/src/commands/ui/assets",
	);
	await replaceVendoredAssets({
		buildDirectory,
		destinationDirectory,
		manifest: second,
		provenance: {
			webVersion: packageJson.version,
			uiSourceCommit: sourceCommit,
			assetManifestSha256: second.manifestSha256,
		},
	});
	console.log(
		`Vendored ${second.assets.length} morphir-web assets from ${sourceCommit}`,
	);
}

if (import.meta.main) {
	main().catch((error: unknown) => {
		console.error(`error: ${error instanceof Error ? error.message : String(error)}`);
		process.exit(1);
	});
}
