/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  ///tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'link',
      label: 'Introduction',
      href: '#'
    },
    {
      type: 'category',
      label: 'Overview',
      items: [
          'intro',
          'morphir-entail',
          'what-is-it-about',
          'domain-model',
          'model-versioning',
          'modeling-entire-application',
          'modeling-database-developers',
          'modeling-financial-concepts'
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
          "installation",
          "editor-setup",
          'morphir-testing-setup',
          'installation-and-usage'
      ]
    },
    {
      type: 'category',
      label: 'Concepts',
      items: []
    },
    {
      type: 'category',
      label: 'Integration Guides',
      items: [
          'scala-backend',
          'scala-codecs',
          'codec-docs',
          'generate-scala-test-case',
          'morphir-spark',
          'spark-backend-api',
          'spark-testing-framework',
          'spark-optional-values',
          'spark-backend-joins',
          'spark-backend-relational',
          'morphir-cadl-mapping',
          'insight-api-guide',
          'morphir-typescript',
          'typescript-api',
          'relational-backend',
          'springboot-generator',
          'json-schema-sample',
          'json-schema-mappings',
          'json-schema-enabled-decorator',
          'json-schema-config',
          'json-schema-backend-test',
          'json-schema-backend-test2',
          'json-codecs-doc',
          'decorations-users-guide',
          'custom-attributes-users-guide'
      ]
    },
    {
      type: 'category',
      label: 'HowTos and Tutorials',
      items: [
          'modeling-database-developers',
          'modeling-financial-concepts',
          'publishing-elm-package',
          'morphir-quick-start',
          'generating-json-schema',
        {
          type: 'link',
          label: 'Surfing Board Tutorial',
          href: 'https://github.com/stephengoldbaum/morphir-examples/tree/master/tutorial'
        }
      ]
    },
    {
      type: 'category',
      label: 'Contribution Guide',
      items: [
          'code-of-conduct',
          'contribution-guide',
          'contribution-and-governance-policies',
          'contributing-to-morphir'
      ]
    },
    {
      type: 'category',
      label: 'Frequently Asked Questions',
      items: []
    },
    {
      type: 'category',
      label: 'Further Readings',
      items: [
          'functional-programming',
          'dev-bots',
          'cli-cli2-merging',
          'results-in-elm',
          'user-guide-readme',
          'testing-framework',
          'table-template',
          'automating-regtech',
          'morphir-elm-commands-processing',
          'morphir-community',
          'adr-for-morphir-cli',
          'media-about-morphir',
          'soul-application',
          'error-append-not-supported',
          'command-line-tools'
      ]
    }
  ],

};

module.exports = sidebars;
