/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Automatically generate sidebar from the docs folder structure
  // This allows the sidebar to reflect the new organized directory layout
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'concepts/introduction-to-morphir',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'getting-started' }
      ],
    },
    {
      type: 'category',
      label: 'CLI Preview',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'cli-preview' }
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'concepts' }
      ],
    },
    {
      type: 'category',
      label: 'Designs',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Drafts',
          items: [{ type: 'autogenerated', dirName: 'design/draft' }],
        },
        {
          type: 'category',
          label: 'Proposals',
          items: [{ type: 'autogenerated', dirName: 'design/proposals' }],
        },
        {
          type: 'category',
          label: 'RFCs',
          items: [{ type: 'autogenerated', dirName: 'design/rfcs' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Specifications',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Drafts',
          items: [{ type: 'autogenerated', dirName: 'spec/draft' }],
        },
        { type: 'doc', id: 'spec/index', label: 'Overview' },
        {
          type: 'category',
          label: 'Morphir IR',
          items: [{ type: 'autogenerated', dirName: 'spec/ir' }],
        },
        {
          type: 'category',
          label: 'Morphir JSON',
          items: [{ type: 'autogenerated', dirName: 'spec/morphir-json' }],
        },
        {
          type: 'category',
          label: 'Morphir TOML',
          items: [{ type: 'autogenerated', dirName: 'spec/morphir-toml' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'User Guides',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'user-guides' }
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'reference' }
      ],
    },
    {
      type: 'category',
      label: 'Developer Guides',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'developers' }
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'use-cases' }
      ],
    },
    {
      type: 'category',
      label: 'Community',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'community' }
      ],
    },
    // Keep the existing ecosystem and special categories that are not part of the main reorganization
    {
      type: 'category',
      label: 'Ecosystem',
      collapsed: true,
      items: [
        {type: 'category', label: 'Morphir Scala', items: [
          'scala/morphir-scala',
          'scala/morphir-scala-support',
          { type: 'category',
            label: 'Morphir Data Model',
            items:[
              'scala/datamodel/datamodel',
              'scala/datamodel/schema',
              'scala/datamodel/primitives',
              'scala/datamodel/lists',
              'scala/datamodel/maps',
              'scala/datamodel/records',
              'scala/datamodel/enums',
            ]
          }
        ]
      },
      ]
    },
  ]
};

module.exports = sidebars;
