/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  ///tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'link',
      label: 'Introduction',
      href: '#'
    },
    {
      type: 'category',
      label: 'Overview',
      items: ['intro', 'application-article', 'domain-model', 'modeling-entire-application'],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: ["installation",  "editor-setup"]
    },
    {
      type: 'category',
      label: 'Concepts',
      items: []
    },
    {
      type: 'category',
      label: 'Integration Guides',
      items: [
          'morphir-spark',
          'morphir-cadl-mapping',
          'insight-api-guide',
          'morphir-typescript',
          'relational-backend'
      ]
    },
    {
      type: 'category',
      label: 'HowTos and Tutorials',
      items: [
          'modeling-database-developers',
          'modeling-financial-concepts',
          'publishing-elm-package',
        {
          type: 'link',
          label: 'Surfing Board Tutorial',
          href: 'https://github.com/stephengoldbaum/morphir-examples/tree/master/tutorial'
        }
      ]
    },
    {
      type: 'category',
      label: 'Contribution Guide',
      items: ['code-of-conduct', 'contribution-guide', 'contribution-and-governance-policies']
    },
    {
      type: 'category',
      label: 'Frequently Asked Questions',
      items: []
    },
    {
      type: 'category',
      label: 'Further Readings',
      items: ['dev-bots', 'cli-cli2-merging']
    }
  ],

};

module.exports = sidebars;
