name: CI - Check
on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
          - name: Checkout current branch
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Setup Java
            uses: graalvm/setup-graalvm@v1
            with:
                java-version: ${{ matrix.jvm }}
                version: "latest"
                github-token: ${{ secrets.GITHUB_TOKEN }}
                components: "native-image"
          - name: Cache scala dependencies
            uses: coursier/cache-action@v6

          - name: Lint code
            run: ./mill -i Alias/lint 